apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-app.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - host: argo-cd.backend-spring-app.com
      http:
        paths:
          - path: /spring-app
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}